### ISSUE TITLE
申請の修正で添付ファイルが反映されない

### ISSUE THREAD

**Issue by naohanpen** [sohosai/sos24-server#320]
200 OK が帰ってきてはいますが、申請の修正で添付ファイルの変更が反映されません。
エラーの原因は分かりませんでしたが、新規作成時も同様のリクエストが送られています。

```
/forms/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

```
{
  "title": "申請太郎",
  "description": "せつめい",
  "starts_at": "1999-12-31T16:01:00.000Z",
  "ends_at": "9999-09-08T15:00:00.000Z",
  "categories": ["foods_with_kitchen"],
  "attributes": ["academic"],
  "attachments": [
    "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  ],
  "items": []
}
```

### 関係がありそうなところ
- https://github.com/sohosai/sos24-server/blob/ab1f58f9d673c29bf5f42abdd73d6e9a3c7148c9/crates/sos24-presentation/src/model/form.rs#L92C1-L107C2

- https://github.com/sohosai/sos24-server/blob/ab1f58f9d673c29bf5f42abdd73d6e9a3c7148c9/crates/sos24-use-case/src/form/interactor/update.rs#L72C3-L76C41

**Comment by arata-nvm** [comment]
詳細な調査ありがとうございます :bow:

先ほど調べてみたところ、以下のコードが悪いということがわかりました。
https://github.com/sohosai/sos24-server/blob/ab1f58f9d673c29bf5f42abdd73d6e9a3c7148c9/crates/sos24-infrastructure/src/form.rs#L313-L321

これは`PUT /forms/:form_id`のリクエストを受けて、その変更をMongoDBに反映させる処理をしているコードです。ここで`attachments`も更新すべきところ、それをしていないので変更が反映されないという顛末だったようです。

このタスクは @naohanpen くんにアサインしても問題ないですか？今いろいろなタスクを抱えていると思うので、問題があれば教えてください！

**Comment by naohanpen** [comment]
@arata-nvm 
そうだったんですね💦
ありがとうございます
自分 Rust 書けないので、他の方にお願いしたいです🙏
